[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@zk-kit/=node_modules/@zk-kit',
]
optimizer = true
optimizer_runs = 200
